CREATE DATABASE IF NOT EXISTS bode_do_no;
USE bode_do_no;

CREATE TABLE IF NOT EXISTS users(
    id BIGINT(255) AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP
);